<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <PackageDescription>Repository pattern implementations for MongoDB using Dilcore DocumentDb</PackageDescription>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Dilcore.DocumentDb.MongoDb.Abstractions\Dilcore.DocumentDb.MongoDb.Abstractions.csproj" />
      <ProjectReference Include="..\Dilcore.DocumentDb.MongoDb\Dilcore.DocumentDb.MongoDb.csproj" />
    </ItemGroup>

</Project>
