<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>disable</Nullable>
        <LangVersion>latest</LangVersion>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Dilcore.DocumentDb.Abstractions\Dilcore.DocumentDb.Abstractions.csproj" />
      <ProjectReference Include="..\Dilcore.DocumentDb.MongoDb.Abstractions\Dilcore.DocumentDb.MongoDb.Abstractions.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Dilcore.Configuration.Abstractions" />
      <PackageReference Include="FluentValidation" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
      <PackageReference Include="MongoDB.Driver" />
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="Dilcore.DocumentDb.MongoDb.IntegrationTests" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Configuration\Database\" />
    </ItemGroup>
</Project>
