<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <PackageDescription>MongoDB implementation for Dilcore DocumentDb with configuration and dependency injection support</PackageDescription>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Dilcore.DocumentDb.Abstractions\Dilcore.DocumentDb.Abstractions.csproj" />
      <ProjectReference Include="..\Dilcore.DocumentDb.MongoDb.Abstractions\Dilcore.DocumentDb.MongoDb.Abstractions.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="FluentValidation" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
      <PackageReference Include="MongoDB.Driver" />
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="Dilcore.DocumentDb.MongoDb.IntegrationTests" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Configuration\Database\" />
    </ItemGroup>

</Project>
