<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>disable</Nullable>
        <LangVersion>latest</LangVersion>
        <RootNamespace>Dilcore.DocumentDb.Abstractions</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="FluentResults" />
      <PackageReference Include="MongoDB.Driver" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Dilcore.DocumentDb.Abstractions\Dilcore.DocumentDb.Abstractions.csproj" />
    </ItemGroup>

</Project>
