<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
        <RootNamespace>Dilcore.MongoDB.ArchitectureTests</RootNamespace>
        <AssemblyName>Dilcore.MongoDB.ArchitectureTests</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Shouldly" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" />
        <PackageReference Include="NUnit" />
        <PackageReference Include="NUnit3TestAdapter" />
        <PackageReference Include="NUnit.Analyzers">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="coverlet.collector">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\src\Dilcore.MongoDB.Abstractions\Dilcore.MongoDB.Abstractions.csproj" />
      <ProjectReference Include="..\..\src\Dilcore.MongoDB\Dilcore.MongoDB.csproj" />
      <ProjectReference Include="..\..\src\Dilcore.MongoDB.SystemTextJson\Dilcore.MongoDB.SystemTextJson.csproj" />
      <ProjectReference Include="..\..\src\Dilcore.MongoDB.NewtonsoftJson\Dilcore.MongoDB.NewtonsoftJson.csproj" />
    </ItemGroup>

</Project>
