# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pr:
 branches:
   include:
     - '*'

parameters:
  - name: runBuildStage
    displayName: 'Run Build Stage'
    default: false
    type: boolean
    values:
      - true
      - false

variables:
  BuildConfiguration: 'Release'
  Environment: 'Development'
  AzureServicesAuthConnectionString: 'RunAs=Developer;DeveloperTool=AzureCli'
  major: 1
  minor: 0
  patch: $(Revision)
  version: $(major).$(minor).$(patch)
  Revision: $[counter(variables['Build.SourceBranchName'], 1)]
  ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:
   versionSuffix: ''
  ${{ if ne( variables['Build.SourceBranchName'], 'main') }}:
   versionSuffix: -prerelease
  packageVersion: ${{ variables.version }}${{ variables.versionSuffix }}

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Build
    displayName: "Build Sources"
    jobs:
      - job: BuildJob
        condition: or(eq(variables['Build.Reason'], 'PullRequest'), eq(${{ parameters.runBuildStage }}, true))
        steps:
        - task: UseDotNet@2
          displayName: 'Install .NET 8'
          inputs:
            packageType: 'sdk'
            version: '8.x'
        - task: DotNetCoreCLI@2
          displayName: 'Restore Nuget Packages'
          inputs:
            command: 'restore'
            projects: '**/*.csproj'
            feedsToUse: 'select'
            vstsFeed: '77bf910c-edc3-46f5-ac83-ee65eb22a5d9'
        - task: DotNetCoreCLI@2
          displayName: '.NET Build'
          inputs:
            command: 'build'
            projects: '**/*.csproj'
            arguments: '--no-restore --configuration $(BuildConfiguration)'
        - task: DotNetCoreCLI@2
          inputs:
            command: 'test'
            projects: '*.sln'
            arguments: '--configuration $(BuildConfiguration) --no-restore --logger trx'
        - task: PublishTestResults@2
          inputs:
            testRunner: VSTest
            testResultsFiles: '**/*.trx'
            
  - stage: NugetPackAndPush
    condition: and(in(dependencies.Build.result, 'Succeeded', 'SucceededWithIssues', 'Skipped'), ne(variables['Build.Reason'], 'PullRequest'))
    jobs:
      - job: NugetPackAndPush
        displayName: "NuGet Pack and Push"
        steps:
          - task: NuGetToolInstaller@1
            displayName: "NuGet Install"
            inputs:
              versionSpec: 
              checkLatest: true
          - task: DotNetCoreCLI@2
            displayName: 'Restore Nuget Packages'
            inputs:
              command: 'restore'
              projects: '**/*.csproj'
              feedsToUse: 'select'
              vstsFeed: '77bf910c-edc3-46f5-ac83-ee65eb22a5d9'
          - task: DotNetCoreCLI@2
            displayName: "Nuget Pack"
            inputs:
              command: 'pack'
              packagesToPack: 'src/**/**.csproj'
              versioningScheme: 'byEnvVar'
              versionEnvVar: 'packageVersion'
              buildProperties: '--no-restore'
          - task: DotNetCoreCLI@2
            displayName: "NuGet Push"
            inputs:
              command: 'push'
              packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
              nuGetFeedType: 'internal'
              publishVstsFeed: '77bf910c-edc3-46f5-ac83-ee65eb22a5d9'