# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - main

pr:
  branches:
    include:
      - main
  paths:
    include:
      - 'src/**/*'

pool:
  vmImage: 'ubuntu-latest'

resources:
 repositories:
   - repository: 'yaml-templates'
     type: git
     name: 'Common Development/Yaml-Templates'

variables:
  - template: 'variables/global.yml@yaml-templates'
  - template: 'variables/nuget.variables.yml'

name: '$(major).$(minor).$(revision)'

extends:
  template: dotnet/stages/dotnet-nuget.yml@yaml-templates
  parameters:
    major: $(major)
    minor: $(minor)
    revision: $(revision)
    projects:
      - 'src/**/*.csproj'
